# Trilha prática de Álgebra Linear em Python

Clique nos links para ver as explicações no YouTube e reproduza os exercícios nas células abaixo.

## [1) Inner or Dot Product of Two n-vectors](https://www.youtube.com/watch?v=hDoGgBRHJsc&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=1)

In [ ]:
import numpy as np

x = np.array([-10, 0, 10])
p = np.array([0.1, 0.4, 0.5])

In [ ]:
np.inner(x, p)

4.0

In [ ]:
x.transpose().dot(p)

4.0

In [ ]:
x @ p

4.0

## [2) Euclidean Norm of an n-vector](https://www.youtube.com/watch?v=b3jmal-YEJQ&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=2)

In [ ]:
import numpy as np

e = np.array([-3, 2, 1, -1, 1])

In [ ]:
np.linalg.norm(e)

4.0

In [ ]:
np.linalg.norm(e) / np.sqrt(len(e))

1.7888543819998317

### Distance

In [ ]:
u = np.array([0, 3])
v = np.array([4, 0])

In [ ]:
np.linalg.norm(u-v)

5.0

## [3) Linear Combination of a Set of Vectors](https://www.youtube.com/watch?v=KpV_RQwuEq8&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=3)

In [ ]:
from sympy import *
init_printing()

In [ ]:
Matrix(2, 3, [1, -1, 2, 1, 2, 3]).rref()

⎛⎡1  0  7/3⎤        ⎞
⎜⎢         ⎥, (0, 1)⎟
⎝⎣0  1  1/3⎦        ⎠

## [4) Linear Dependence vs Independence](https://www.youtube.com/watch?v=_U6gwFvk6Xc&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=4)

## [5) Linear Independence: Determinant and Inverse](https://www.youtube.com/watch?v=-kTeD4Q82Bk&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=5)

In [ ]:
from sympy import *
init_printing()

I = Matrix(3,3, [1,0,4, -1,2,0, 4,-3,-3])
I

⎡1   0   4 ⎤
⎢          ⎥
⎢-1  2   0 ⎥
⎢          ⎥
⎣4   -3  -3⎦

In [ ]:
I.det()

In [ ]:
I.inv()

⎡3/13  6/13   4/13 ⎤
⎢                  ⎥
⎢       19         ⎥
⎢3/26   ──    2/13 ⎥
⎢       26         ⎥
⎢                  ⎥
⎣5/26  -3/26  -1/13⎦

## [6) Python: Reduced Row Echelon Form](https://www.youtube.com/watch?v=47H3h7ssa6M&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=6)

In [ ]:
from sympy import *
init_printing()

aug_X = Matrix([[1,3,5,-1], [2,2,-1,1], [1,3,2,2]])
aug_X

⎡1  3  5   -1⎤
⎢            ⎥
⎢2  2  -1  1 ⎥
⎢            ⎥
⎣1  3  2   2 ⎦

In [ ]:
aug_X.rref()

⎛⎡1  0  0  -2⎤           ⎞
⎜⎢           ⎥           ⎟
⎜⎢0  1  0  2 ⎥, (0, 1, 2)⎟
⎜⎢           ⎥           ⎟
⎝⎣0  0  1  -1⎦           ⎠

## [7) Matrix Inverse in Python](https://www.youtube.com/watch?v=mrXcNVB0l1Y&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=7)

In [ ]:
import numpy as np

A = np.array([[1,2,1], [4,4,5], [6,7,7]])
A

array([[1, 2, 1],
       [4, 4, 5],
       [6, 7, 7]])

In [ ]:
inverse = np.linalg.inv(A)
inverse

array([[-7., -7.,  6.],
       [ 2.,  1., -1.],
       [ 4.,  5., -4.]])

In [ ]:
np.round(inverse @ A)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [ ]:
np.round(A @ inverse)

array([[ 1., -0.,  0.],
       [-0.,  1.,  0.],
       [ 0., -0.,  1.]])

## [8) Determinant and Inverse Matrix in Sympy](https://www.youtube.com/watch?v=Gdpm7WBJLSg&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=8)

In [ ]:
from sympy import *
init_printing()

a, b, c, d = symbols('a, b, c, d')
A = Matrix([[a,b], [c,d]])
A

⎡a  b⎤
⎢    ⎥
⎣c  d⎦

In [ ]:
A.det()

In [ ]:
A.inv()

⎡    d         -b    ⎤
⎢─────────  ─────────⎥
⎢a⋅d - b⋅c  a⋅d - b⋅c⎥
⎢                    ⎥
⎢   -c          a    ⎥
⎢─────────  ─────────⎥
⎣a⋅d - b⋅c  a⋅d - b⋅c⎦

## [9) Eigenvalue and Eivenvector in Synpy](https://www.youtube.com/watch?v=MqBoJlgKEuI&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=10)

In [ ]:
from sympy import *
init_printing()

A = Matrix([[-1,3], [2,0]])
A

⎡-1  3⎤
⎢     ⎥
⎣2   0⎦

In [ ]:
A.eigenvects()

⎡⎛       ⎡⎡-3/2⎤⎤⎞  ⎛      ⎡⎡1⎤⎤⎞⎤
⎢⎜-3, 1, ⎢⎢    ⎥⎥⎟, ⎜2, 1, ⎢⎢ ⎥⎥⎟⎥
⎣⎝       ⎣⎣ 1  ⎦⎦⎠  ⎝      ⎣⎣1⎦⎦⎠⎦

## [10) Eigenvalue and Eigenvector in Sympy](https://www.youtube.com/watch?v=MqBoJlgKEuI&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=10)

In [ ]:
from sympy import *
init_printing()

A = Matrix([[-1,3], [2,0]])
A

⎡-1  3⎤
⎢     ⎥
⎣2   0⎦

In [ ]:
A.eigenvects()

⎡⎛       ⎡⎡-3/2⎤⎤⎞  ⎛      ⎡⎡1⎤⎤⎞⎤
⎢⎜-3, 1, ⎢⎢    ⎥⎥⎟, ⎜2, 1, ⎢⎢ ⎥⎥⎟⎥
⎣⎝       ⎣⎣ 1  ⎦⎦⎠  ⎝      ⎣⎣1⎦⎦⎠⎦

## [11) Standard Basis Vectors](https://www.youtube.com/watch?v=zLoz3tYoDK0&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=11)

## [12) Matrix Transformation](https://www.youtube.com/watch?v=sRvfTly2c08&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=12)

## [13) Normalized and Unit Vector in Python](https://www.youtube.com/watch?v=UN3ytcnDZa4&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=13)

In [ ]:
from sympy import *
init_printing()

v = Matrix([[2,2, -1]])
v

[2  2  -1]

In [ ]:
v.norm()

In [ ]:
u = v.normalized()
u

[2/3  2/3  -1/3]

In [ ]:
v / v.norm()

[2/3  2/3  -1/3]

In [ ]:
u.norm()

## [14) Formula to Calculate the Angle between Two Vectors](https://www.youtube.com/watch?v=9cF3Nougasg&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=14)

## [15) Correlation as the Cosine of the Angle between Two Vectors](https://www.youtube.com/watch?v=PmsqpbOAMvo&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=15)

## [16) Orthogonal Projection: Formula Derivation](https://www.youtube.com/watch?v=S8hAmBAbGWQ&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=16)

## [17) Cross Product in Python](https://www.youtube.com/watch?v=tZu91n2cM0A&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=17)

In [ ]:
from sympy import *
init_printing()

u = Matrix([[1,2,-2]])
v = Matrix([[3,0,1]])

In [ ]:
u

[1  2  -2]

In [ ]:
v

[3  0  1]

In [ ]:
u.cross(v)

[2  -7  -6]

In [ ]:
from sympy.abc import a, b, c, d, e, f

x = Matrix([[a,b,c]])
x

[a  b  c]

In [ ]:
y = Matrix([[d,e,f]])
y

[d  e  f]

In [ ]:
x.cross(y)

[b⋅f - c⋅e  -a⋅f + c⋅d  a⋅e - b⋅d]

## [18) Eigenvalue, Trace, and Determinant](https://www.youtube.com/watch?v=fqNk2XNZVhg&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=18)

## [19) Python: Eigenvalue, Trace, and Determinant](https://www.youtube.com/watch?v=5gWQGb-XQ48&list=PLOQU3c_3DSpK4D0k3OLj3HLZ7LMhb9GvB&index=19)

In [ ]:
from sympy import *
init_printing()

A = Matrix([[4, 2], [1,3]])
A

⎡4  2⎤
⎢    ⎥
⎣1  3⎦

In [ ]:
A.eigenvals()

In [ ]:
A.trace()

In [ ]:
A.det()